//	stdafx.h - Generated by the "Microsoft Visio 2010 SDK Add-on Wizard"
//
//	<summary>
//	This file is the include file for standard system include files,
//	or project specific include files that are used frequently, but
//	are changed infrequently.
//	</summary>
//	

#pragma once


//	Don't warn if inline functions are not inlined (warning level
//	4 warning #4710).
#pragma warning(disable:4710)

// Import the Visio type library with named GUIDs for the
// type library entries.
#import "C:\Program Files (x86)\Microsoft Office\Office15\VisSDK\Libraries\Typelib\visio.tlb" named_guids

//{{AFX_INSERT_LOCATION}}
//	Microsoft Visual C++ will insert additional declarations immediately before the previous line.
