//	TestAddonVsl.h - Generated by the "Microsoft Visio 2010 SDK Add-on Wizard"
//
//	<summary>
//	This is the main header file for the TestAddonVsl application.
//	</summary>
//	

#pragma once

#if defined VADDON_MFC
#ifndef __AFXWIN_H__
	#error include 'stdafx.h' before including this file for PCH
#endif
#endif

#include "resource.h"		//	main symbols


