//	TestAddonVsl.cpp - Generated by the "Microsoft Visio 2010 SDK 
//					Add-on Wizard"
//
//	<summary>
//	This source file contains the initialization routines 
//	for the VSL.
//	</summary>
//	

#include "stdafx.h"
#include <tchar.h>
#include <strsafe.h>

#ifndef INITGUID
#define INITGUID
#endif
#include <objbase.h>
#include <initguid.h>

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

#include "TestAddonVsl.h"



