//	vao_all.cpp - Generated by the "Microsoft Visio 2010 SDK Add-on Wizard"
//
//	<summary>
//	This file references the necessary vao_src\*.cpp files which should be 
//	included in projects with .vsl targets.
//	</summary>
//	

#include "stdafx.h"
#include "vTestAddonVsl.h"
#include "addsink.cpp"		//	For hooking up to Visio events

#include "vaddon.cpp"		//	The "easy-to-subclass" VAddon

extern "C" 
{
	#include "vao.c"		//	.vsl utility functions
}

#if !defined VADDON_MFC 
extern "C" 
{
	#include "vdllmain.c"
}
#endif
