//	stdafx.cpp - Generated by the "Microsoft Visio 2010 SDK Add-on Wizard"
//
//	<summary>
//	This is the source file for building the pre-compiled header file
//	$$root$$.pch.
//	</summary>
//	

#include "stdafx.h"



