//	TestAddonExe.cpp - Generated by the "Microsoft Visio 2010 SDK 
//					Add-on Wizard"
//
//	<summary>
//	This source file defines the class behaviors for the 
//	application.
//	</summary>
//	

#include "stdafx.h"
#ifndef INITGUID
#define INITGUID
#endif
#include <objbase.h>
#include <initguid.h>
#include "TestAddonExe.h"


