//	vao_all.cpp - Generated by the "Microsoft Visio 2010 SDK Add-on Wizard"
//
//	<summary>
//	This file references the necessary vao_src\*.cpp files which should be 
//	included in projects with .exe targets.
//	</summary>
//	

#include "stdafx.h"
#include "vTestAddonExe.h"
#include "addsink.cpp"		//	For hooking up to Visio events
#include "vaddon.cpp"		//	The "easy-to-subclass" VAddon

extern "C" 
{
	#include "vao.c"		//	.exe utility functions
}

#include "vexe.cpp"
