//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.8669
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisioWixExtension
{
    using System;
    using System.Reflection;
    using System.Resources;
    using Microsoft.Tools.WindowsInstallerXml;
    
    
    public class VisioErrorEventArgs : WixErrorEventArgs
    {
        
        private static ResourceManager resourceManager = new ResourceManager("VisioWixExtension.Data.Messages", Assembly.GetExecutingAssembly());
        
        public VisioErrorEventArgs(SourceLineNumberCollection sourceLineNumbers, int id, string resourceName, params object[] messageArgs) : 
                base(sourceLineNumbers, id, resourceName, messageArgs)
        {
        }
        
        public override ResourceManager ResourceManager
        {
            get
            {
                return resourceManager;
            }
        }
    }
    
    public sealed class VisioErrors
    {
        
        private VisioErrors()
        {
        }
        
        public static VisioErrorEventArgs InvalidVisioEdition(SourceLineNumberCollection sourceLineNumbers, string value)
        {
            return new VisioErrorEventArgs(sourceLineNumbers, 6501, "VisioErrors_InvalidVisioEdition_1", value);
        }
        
        public static VisioErrorEventArgs InvalidLanguage(SourceLineNumberCollection sourceLineNumbers, string value)
        {
            return new VisioErrorEventArgs(sourceLineNumbers, 6502, "VisioErrors_InvalidLanguage_1", value);
        }
        
        public static VisioErrorEventArgs InvalidUint(SourceLineNumberCollection sourceLineNumbers, string attributeName, string value)
        {
            return new VisioErrorEventArgs(sourceLineNumbers, 6503, "VisioErrors_InvalidUint_1", attributeName, value);
        }
        
        public static VisioErrorEventArgs UsingPublish(SourceLineNumberCollection sourceLineNumbers)
        {
            return new VisioErrorEventArgs(sourceLineNumbers, 6504, "VisioErrors_UsingPublish_1");
        }
        
        public static VisioErrorEventArgs FileIdentifierNotFound(string fileId)
        {
            return new VisioErrorEventArgs(null, 6505, "VisioErrors_FileIdentifierNotFound_1", fileId);
        }
        
        public static VisioErrorEventArgs AddinNotFound(string filePath)
        {
            return new VisioErrorEventArgs(null, 6506, "VisioErrors_AddinNotFound_1", filePath);
        }
        
        public static VisioErrorEventArgs InvalidAddinType(SourceLineNumberCollection sourceLineNumbers, string value)
        {
            return new VisioErrorEventArgs(sourceLineNumbers, 6507, "VisioErrors_InvalidAddinType_1", value);
        }
        
        public static VisioErrorEventArgs UnknownAddinType(string value)
        {
            return new VisioErrorEventArgs(null, 6508, "VisioErrors_UnknownAddinType_1", value);
        }
        
        public static VisioErrorEventArgs InternalException(string value)
        {
            return new VisioErrorEventArgs(null, 6509, "VisioErrors_InternalException_1", value);
        }
    }
    
    public class VisioWarningEventArgs : WixWarningEventArgs
    {
        
        private static ResourceManager resourceManager = new ResourceManager("VisioWixExtension.Data.Messages", Assembly.GetExecutingAssembly());
        
        public VisioWarningEventArgs(SourceLineNumberCollection sourceLineNumbers, int id, string resourceName, params object[] messageArgs) : 
                base(sourceLineNumbers, id, resourceName, messageArgs)
        {
        }
        
        public override ResourceManager ResourceManager
        {
            get
            {
                return resourceManager;
            }
        }
    }
    
    public sealed class VisioWarnings
    {
        
        private VisioWarnings()
        {
        }
        
        public static VisioWarningEventArgs InvalidFileExtension(SourceLineNumberCollection sourceLineNumbers, string fileName, string expectedVisioContentType)
        {
            return new VisioWarningEventArgs(sourceLineNumbers, 6600, "VisioWarnings_InvalidFileExtension_1", fileName, expectedVisioContentType);
        }
    }
}
